### ISSUE TITLE
F.__iand__ method doesn't construct valid URL

### ISSUE THREAD

**Issue by chrisluedtke** [UrbanCCD-UChicago/aot-client-py#7]
[`F.__iand__`](https://github.com/UrbanCCD-UChicago/aot-client-py/blob/master/aot_client/filters.py#L53)

``` python
from aot_client import AotClient
from aot_client import F

client = AotClient()

f = F()
f &= ('sensor', 'image.image_detector.person_total')
f &= ('sensor', 'image.image_detector.car_total')

observations = client.list_observations(filters=f)
```
`HTTPError: 500 Server Error: Internal Server Error for url: https://api.arrayofthings.org/api/observations?sensor%5B%5D=eq%3Aimage.image_detector.person_total&sensor%5B%5D=eq%3Aimage.image_detector.car_total`

**Comment by vforgione** [comment]
This seems like some sort of regression in the API -- I tried manually `curl`ing the same request and it blew up.

I'm low on bandwidth right now, so it's difficult to put an ETA on this.

**Comment by vforgione** [comment]
I found myself with some time to fix this. It's good to go now. I also found the same bug applied to array values for nodes and took care of that too.
